### PR TITLE
Split datasource role into org and space role datasource

### LINKED ISSUE #23: [BUG] Inconsistency of resources for roles and data sources
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform provider are you using?

1.0.0-rc1

### What version of the Terraform CLI are you using?

1.9.5

### What CF API version are you using?

3.137

### What type of issue are you facing

bug report

### Describe the bug

The resources and data sources to assign and read roles of users are not consistent. While the resources distinguish the levels of organization and space ([org_role](https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/resources/org_role), [space_role](https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/resources/space_role)), the data source is a single one for all levels ([role](https://registry.terraform.io/providers/cloudfoundry/cloudfoundry/latest/docs/data-sources/role)).

### Expected Behavior

Data sources for the org and space level are available in analogy to the resources

### Steps To Reproduce

n/a

### Your Terraform Configuration

```hcl
n/a
```

### Roles

n/a

### Add screenshots to help explain your problem

n/a

### Additional context

n/a

### PR DESCRIPTION
**Pull request by Dray56**
## Purpose

- fix #23 

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Pull Request Type

What kind of change does this Pull Request introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation content changes
- [ ] Other... Please describe:

## How to Test

- Test the code via automated test

```bash
go test ./...
```

- Additional test steps

```
...
```

## What to Check

Verify that the following are valid:

- Automated tests are executed successfully

- ...

## Checklist for reviewer

The following organizational tasks must be completed before merging this PR:

- [ ] The PR is assigned to the Terraform project and a status is set (typically "in review").
- [ ] The PR has the matching labels assigned to it.
- [ ] The PR has a milestone assigned to it.
- [ ] If the PR closes an issue, the issue is referenced.
- [ ] Possible follow-up items are created and linked.

### CODE REVIEW

File: internal/provider/types_role.go [hunk 1]
```diff
@@ -41,10 +41,18 @@ type orgRoleType struct {
 	UpdatedAt    types.String `tfsdk:"updated_at"`
 }
 
-type roleDatasourceType struct {
+type spaceRoleDatasourceType struct {
+	Type      types.String `tfsdk:"type"`
+	User      types.String `tfsdk:"user"`
+	Space     types.String `tfsdk:"space"`
```
Comment (vipinvkmenon) [inline internal/provider/types_role.go:47]: `space_guid` & `org_guid` would be more precise right (Here and in the data source)?

Comment (Dray56) [reply internal/provider/types_role.go:47]: The general convention we have followed is that if only space or org is mentioned by default it means only guid but if something like space_name or org_name is present like in app resource then it implies something other than guid.

**Review by vipinvkmenon — APPROVED** [review]
